### ISSUE TITLE
Why i'm not able to claim season 1 airdrop?

### ISSUE THREAD

**Issue by Ashwin3454** [Desamod/CatsGangBot#5]
i had 16K cats
![image](https://github.com/user-attachments/assets/c052432a-6650-4e03-a86e-4bcebe7c6ed2)

**Comment by Desamod** [comment]
To receive a drop, you need to fulfill one of the criteria:
1. Possession of an OG pass  
2. At least 1 transactions  
3. A minimum of 5 frens, 15 tasks and 5 avatar upgrades
